/**
 * Comprehensive English to Greek translation dictionary for Gematria & vocabulary terms
 */
export const COMMON_ENGLISH_GREEK_TRANSLATIONS: Record<string, string> = {
  "COMPUTER": "Υπολογιστής",
  "PARTNERS": "Συνέταιροι / Συνεργάτες",
  "VACCINATION": "Εμβολιασμός",
  "CORONA VACCINE": "Εμβόλιο Κορονοϊού",
  "MARK OF BEAST": "Το Χάραγμα του Θηρίου",
  "NEW YORK": "Νέα Υόρκη",
  "THE DRAGON": "Ο Δράκων",
  "LUCIFER HELL": "Εωσφόρος / Κόλαση",
  "DIGITAL ID": "Ψηφιακή Ταυτότητα",
  "GENETIC CODE": "Γενετικός Κώδικας",
  "BIO WEAPON": "Βιολογικό Όπλο",
  "SORCERIES": "Φαρμακείες / Μαγείες",
  "ILLUMINATI": "Οι Πεφωτισμένοι",
  "INSANITY": "Παραφροσύνη / Τρέλα",
  "KISSINGER": "Κίσινγκερ",
  "MONETARY": "Νομισματικός",
  "PAYPAL INC": "Εταιρεία PayPal",
  "INTERNET TECH": "Τεχνολογία Διαδικτύου",
  "RFID CHIP": "Μικροτσίπ RFID",
  "IMAGE OF BEAST": "Η Εικόνα του Θηρίου",
  "GLOBAL LEADER": "Παγκόσμιος Ηγέτης",
  "HOLY BIBLE": "Αγία Γραφή",
  "JESUS IS LORD": "Ο Ιησούς είναι Κύριος",
  "THE MESSIAH": "Ο Μεσσίας",
  "GOD OF ISRAEL": "Ο Θεός του Ισραήλ",
  "ALPHA OMEGA": "Το Άλφα και το Ωμέγα",
  "DIVINE LOVE": "Θεία Αγάπη",
  "THE KINGDOM": "Η Βασιλεία",
  "GOD IS GOOD": "Ο Θεός είναι Αγαθός",
  "THE CHRIST": "Ο Χριστός",
  "PEACE AND SAFETY": "Ειρήνη και Ασφάλεια",
  "UNITED NATIONS": "Ηνωμένα Έθνη",
  "WORLD ORDER": "Παγκόσμια Τάξη",
  "GREAT TRIBULATION": "Μεγάλη Θλίψη",
  "FALSE PROPHET": "Ψευδοπροφήτης",
  "SON OF PERDITION": "Ο Υιός της Απωλείας",
  "TEMPLE OF GOD": "Ο Ναός του Θεού",
  "BOOK OF LIFE": "Το Βιβλίο της Ζωής",
  "SECRET SOCIETY": "Μυστική Εταιρεία",
  "ANCIENT WISDOM": "Αρχαία Σοφία",
  "SACRED GEOMETRY": "Ιερά Γεωμετρία",
  "GOLDEN RATIO": "Χρυσή Τομή",
  "NEW AGE": "Νέα Εποχή",
  "SUN OF GOD": "Ήλιος του Θεού",
  "LIGHT OF WORLD": "Φως του Κόσμου",
  "HOLY GHOST": "Άγιο Πνεύμα",
  "TREE OF LIFE": "Το Δέντρο της Ζωής",
  "KING OF KINGS": "Βασιλεύς των Βασιλέων",
  "LORD OF LORDS": "Κύριος των Κυρίων",
  "ARMAGEDDON": "Αρμαγεδδών",
  "APOCALYPSE": "Αποκάλυψη",
  "REVELATION": "Αποκάλυψη",
  "HEAVEN AND EARTH": "Ουρανός και Γη",
  "ETERNAL LIFE": "Αιώνια Ζωή",
  "KINGDOM OF GOD": "Η Βασιλεία του Θεού",
  "PRINCE OF PEACE": "Άρχων της Ειρήνης",
  "BREAD OF LIFE": "Ο Άρτος της Ζωής",
  "WATER OF LIFE": "Το Ύδωρ της Ζωής",
  "MORNING STAR": "Ο Εωσφόρος / Πρωινός Αστήρ",
  "CORONA": "Στέμμα / Κορώνα",
  "VACCINE": "Εμβόλιο",
  "VIRUS": "Ιός",
  "BEAST": "Θηρίο",
  "DRAGON": "Δράκων",
  "SERPENT": "Όφις / Φίδι",
  "WISDOM": "Σοφία",
  "KNOWLEDGE": "Γνώση",
  "TRUTH": "Αλήθεια",
  "JUSTICE": "Δικαιοσύνη",
  "POWER": "Δύναμη / Εξουσία",
  "GLORY": "Δόξα",
  "HONOR": "Τιμή",
  "AUTHORITY": "Εξουσία",
  "SYSTEM": "Σύστημα",
  "NETWORK": "Δίκτυο",
  "CONTROL": "Έλεγχος",
  "SLAVERY": "Δουλεία",
  "FREEDOM": "Ελευθερία",
  "LIBERTY": "Ελευθερία",
  "DOLLAR": "Δολάριο",
  "CURRENCY": "Νόμισμα",
  "BANK": "Τράπεζα",
  "FEDERAL RESERVE": "Ομοσπονδιακή Τράπεζα (Fed)",
  "LUCIFER": "Εωσφόρος",
  "SATAN": "Σατανάς",
  "DEVIL": "Διάβολος",
  "DEMON": "Δαίμονας",
  "ANGEL": "Άγγελος",
  "ARCHANGEL": "Αρχάγγελος",
  "MICHAEL": "Μιχαήλ",
  "GABRIEL": "Γαβριήλ",
  "RAPHAEL": "Ραφαήλ",
  "URIEL": "Ουριήλ",
  "ISRAEL": "Ισραήλ",
  "JERUSALEM": "Ιερουσαλήμ",
  "ZION": "Σιών",
  "BABYLON": "Βαβυλώνα",
  "ROME": "Ρώμη",
  "ATHENS": "Αθήνα",
  "GREECE": "Ελλάδα",
  "AMERICA": "Αμερική",
  "PRESIDENT": "Πρόεδρος",
  "EMPEROR": "Αυτοκράτορας",
  "KING": "Βασιλιάς",
  "QUEEN": "Βασίλισσα",
  "CROWN": "Στέμμα",
  "THRONE": "Θρόνος",
  "PYRAMID": "Πυραμίδα",
  "EYE": "Οφθαλμός / Μάτι",
  "ALL SEEING EYE": "Παντεπόπτης Οφθαλμός",
  "MASON": "Τέκτονας / Μασόνος",
  "FREEMASON": "Ελευθεροτέκτονας",
  "LODGE": "Στοά",
  "COMPASS": "Διαβήτης",
  "SQUARE": "Γνώμονας / Τετράγωνο",
  "OBELISK": "Οβελίσκος",
  "SOLOMON": "Σολομών",
  "TEMPLE": "Ναός",
  "ALTAR": "Βωμός / Θυσιαστήριο",
  "SACRIFICE": "Θυσία",
  "BLOOD": "Αίμα",
  "COVENANT": "Διαθήκη",
  "ARK": "Κιβωτός",
  "COMMANDMENTS": "Εντολές",
  "LAW": "Νόμος",
  "GRACE": "Χάρις",
  "FAITH": "Πίστη",
  "HOPE": "Ελπίδα",
  "LOVE": "Αγάπη",
  "CHARITY": "Ελεημοσύνη / Αγάπη",
  "MERCY": "Έλεος",
  "JUDGMENT": "Κρίση",
  "RIGHTEOUSNESS": "Δικαιοσύνη",
  "SIN": "Αμαρτία",
  "DEATH": "Θάνατος",
  "RESURRECTION": "Ανάσταση",
  "SALVATION": "Σωτηρία",
  "REDEMPTION": "Απολύτρωση",
};

// Word-by-word simple dictionary for compound phrases
const WORD_DICT: Record<string, string> = {
  "THE": "Ο / Η / Το",
  "OF": "Του / Της",
  "AND": "Και",
  "IN": "Στο / Σε",
  "FOR": "Για",
  "WITH": "Με",
  "TO": "Προς",
  "FROM": "Από",
  "BY": "Υπό / Από",
  "IS": "Είναι",
  "ARE": "Είναι",
  "NOT": "Δεν",
  "GOD": "Θεός",
  "LORD": "Κύριος",
  "KING": "Βασιλιάς",
  "WORLD": "Κόσμος",
  "EARTH": "Γη",
  "SUN": "Ήλιος",
  "MOON": "Σελήνη",
  "STAR": "Αστέρι",
  "LIGHT": "Φως",
  "DARKNESS": "Σκότος",
  "FIRE": "Πυρ / Φωτιά",
  "WATER": "Ύδωρ / Νερό",
  "AIR": "Αήρ / Αέρας",
  "SPIRIT": "Πνεύμα",
  "SOUL": "Ψυχή",
  "BODY": "Σώμα",
  "MIND": "Νους",
  "HEART": "Καρδιά",
  "LIFE": "Ζωή",
  "DEATH": "Θάνατος",
  "MAN": "Άνθρωπος",
  "WOMAN": "Γυναίκα",
  "CHILD": "Παιδί",
  "SON": "Υιός",
  "DAUGHTER": "Θυγατέρα",
  "FATHER": "Πατέρας",
  "MOTHER": "Μητέρα",
  "BROTHER": "Αδελφός",
  "SISTER": "Αδελφή",
  "HOUSE": "Οίκος",
  "CITY": "Πόλις",
  "WAR": "Πόλεμος",
  "PEACE": "Ειρήνη",
  "POWER": "Δύναμη",
  "NUMBER": "Αριθμός",
  "NAME": "Όνομα",
  "WORD": "Λόγος / Λέξη",
  "CODE": "Κώδικας",
  "SECRET": "Μυστικό",
  "HIDDEN": "Κρυμμένο",
  "TRUE": "Αληθινός",
  "FALSE": "Ψευδής",
  "EVIL": "Κακό / Πονηρό",
  "GOOD": "Καλό / Αγαθό",
  "HOLY": "Άγιος",
  "SACRED": "Ιερός",
  "GREAT": "Μέγας",
  "BEAST": "Θηρίο",
  "DRAGON": "Δράκων",
  "MARK": "Χάραγμα / Σημάδι",
  "CHIP": "Τσιπ",
  "CARD": "Κάρτα",
  "BANK": "Τράπεζα",
  "MONEY": "Χρήμα",
  "GOLD": "Χρυσός",
  "SILVER": "Άργυρος",
  "SYSTEM": "Σύστημα",
  "CONTROL": "Έλεγχος",
  "TIME": "Χρόνος",
  "DAY": "Ημέρα",
  "NIGHT": "Νύχτα",
  "YEAR": "Έτος",
  "END": "Τέλος",
  "BEGINNING": "Αρχή",
  "FIRST": "Πρώτος",
  "LAST": "Έσχατος",
  "ONE": "Ένας",
  "TWO": "Δύο",
  "THREE": "Τρία",
  "SEVEN": "Επτά",
  "SIX": "Έξι",
  "NINE": "Εννέα",
  "TEN": "Δέκα",
  "HUNDRED": "Εκατό",
  "THOUSAND": "Χίλια",
};

/**
 * Translate an English word or phrase into Greek
 */
export function translateEnglishToGreek(phrase: string): string | null {
  if (!phrase) return null;
  const clean = phrase.trim().toUpperCase();

  // 1. Direct match in full phrase dictionary
  if (COMMON_ENGLISH_GREEK_TRANSLATIONS[clean]) {
    return COMMON_ENGLISH_GREEK_TRANSLATIONS[clean];
  }

  // 2. Try word-by-word if multi-word phrase
  const parts = clean.split(/\s+/);
  if (parts.length > 1) {
    const translatedParts = parts.map(p => COMMON_ENGLISH_GREEK_TRANSLATIONS[p] || WORD_DICT[p] || p.toLowerCase());
    // Check if at least some words were translated
    const hasTranslation = parts.some(p => COMMON_ENGLISH_GREEK_TRANSLATIONS[p] || WORD_DICT[p]);
    if (hasTranslation) {
      return translatedParts.join(" ");
    }
  } else if (WORD_DICT[clean]) {
    return WORD_DICT[clean];
  }

  return null;
}
